<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:req="http://schematics.merenita.com/gsos/power/request/"
	xmlns:rsp="http://schematics.merenita.com/gsos/power/response/"
	xmlns:flt="http://schematics.merenita.com/gsos/power/fail/" 	
	xmlns:srv="http://schematics.merenita.com/gsos/power/message/"
	targetNamespace="http://schematics.merenita.com/gsos/power/message/">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://schematics.merenita.com/gsos/power/request/"
				schemaLocation="powerrequest.xsd" />
			<xsd:import namespace="http://schematics.merenita.com/gsos/power/response/"
				schemaLocation="powerresponse.xsd" />
			<xsd:import namespace="http://schematics.merenita.com/gsos/power/fail/"
				schemaLocation="powerfail.xsd" />
		</xsd:schema>
	</wsdl:types>
        <wsdl:message name="request">
		<wsdl:part name="request" element="req:powerRequest"/>
	</wsdl:message>
	<wsdl:message name="response">
		<wsdl:part name="response" element="rsp:powerResponse"/>
	</wsdl:message>
	<wsdl:message name="ApplicatieFout">
		<wsdl:part name="ApplicatieFout" element="flt:powerFail"/>
	</wsdl:message>
        <wsdl:portType name="powerSoap">
		<wsdl:operation name="calculatePower">
			<wsdl:input message="srv:request"/>
			<wsdl:output message="srv:response"/>
			<wsdl:fault name="ApplicatieFout" message="srv:ApplicatieFout"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="powerSoap12" type="srv:powerSoap">
		<soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="calculatePower">
			<soap12:operation soapAction="" style="document"/>
			<wsdl:input>
				<soap12:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap12:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="ApplicatieFout">
				<soap12:fault name="ApplicatieFout" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="powerService">
		<wsdl:port name="powerServiceSoap" binding="srv:powerSoap12">
			<soap12:address location="http://gsos.jelleluteijn.com/PowerService.do"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
